workflows:
  build-ios:
    name: Build iOS App (QR Generator)
    environment:
      vars:
        APP_NAME: "qr-pwa"
        APP_ID: "com.example.app"
      flutter: stable
      xcode: latest
      node: 20.17.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
          
      - name: Build React app
        script: |
          npm run build
      - name: Add Capacitor iOS platform
        script: |
          npx cap add ios || echo "iOS platform already exists"
          npx cap copy ios
      - name: CocoaPods install
        script: |
          cd ios/App
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath $CM_BUILD_DIR/output/App.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/output/App.xcarchive \
          -exportOptionsPlist ios/App/exportOptions.plist \
          -exportPath $CM_BUILD_DIR/output
    artifacts:
      - output/*.ipa
    publishing:
      email:
        recipients:
          - your_email@example.com
